name: Build
on: [push, pull_request]
jobs:
  Test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Test scripts
        shell: pwsh
        run: |
          $pesterConfig = @{
            Run = @{
              Exit = $true
            }
            TestResult = @{
              Enabled = $true
              OutputPath = "testResults.xml"
              OutputFormat = "NUnitXML"
            }
            Output = @{
              Verbosity = "Detailed"
            }
          }
          Invoke-Pester -Configuration $pesterConfig
      - name: Upload test results
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: Pester-Test-Results
          path: testResults.xml
  Build:
    runs-on: windows-latest
    needs: Test
    strategy:
      matrix:
        bitness: ['x86', 'x64']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build ${{ matrix.bitness }}
        shell: pwsh
        run: |
          Set-StrictMode -Version Latest
          $ErrorActionPreference = 'Stop'
          $ProgressPreference = 'SilentlyContinue'

          .\build.ps1 .\${{ matrix.bitness }}.json -MSYS2Path C:\msys64
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Installers
          path: bin/
