name: Build
on: [push, pull_request]
jobs:
  Build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        run: |
          Set-StrictMode -Version Latest
          $ErrorActionPreference = 'Stop'
          $ProgressPreference = 'SilentlyContinue'

          .\build.ps1 .\x64.json -MSYS2Path C:\msys64
          .\build.ps1 .\x86.json -MSYS2Path C:\msys64

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: bin/
